# Generated by Django 5.2.4 on 2025-07-14 16:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateField(default=datetime.date.today)),
                ('fecha_salida', models.DateField()),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='confirmada', max_length=50)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfil')),
                ('habitacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.habitacion')),
            ],
        ),
    ]
