# Generated by Django 5.2.4 on 2025-07-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['reserva_id']},
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='reserva',
        ),
    ]
