# Generated by Django 5.2.4 on 2025-07-14 16:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_alter_reserva_options_alter_reserva_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(default=datetime.date.today)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pagada', models.BooleanField(default=False)),
                ('reserva_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.reserva')),
            ],
            options={
                'db_table': 'Factura',
                'ordering': ['fecha_emision'],
            },
        ),
    ]
