# Generated by Django 5.2.4 on 2025-07-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='factura',
            table='factura',
        ),
    ]
