# Generated by Django 5.2.4 on 2025-07-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('habitacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'individual'), ('DOBLE', 'doble'), ('SUITE', 'suite')], default='individual', max_length=50)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'habitacion',
                'ordering': ['habitacion_id'],
            },
        ),
    ]
