# Generated by Django 5.2.4 on 2025-07-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('capacidad_maxima', models.PositiveIntegerField()),
                ('precio_entrada', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'evento',
                'ordering': ['id_evento'],
            },
        ),
    ]
